kind: Pod
apiVersion: v1
metadata:
  namespace: karthik
  name: Resource-pod
  labels:
    name: Resource
    Environment: Dev
    createdBy: karthik
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
      ports:
        - containerPort: 80
