kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: karthik
  name: practice-deployment
  labels:
    name: deployment-pod
    face: frontend
    environment: PROD
    nature: Normal
spec:
  replicas: 3
  selector:
    matchLabels:
      name: deployment-pod
      face: frontend
      environment: PROD
      nature: Normal
  template:
    metadata:
      name: pods
      labels:
        name: deployment-pod
        face: frontend
        environment: PROD
        nature: Normal
    spec:
      containers:
        - name: nginx
          image: nginx:latest
