kind: Pod
apiVersion: v1
metadata:
  namespace: karthik
  name: nginx-pod
  labels:
    name: nginx
    environment: Dev
    createdBy: karthik
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 80
        - containerPort: 8080
