kind: Pod
apiVersion: v1
metadata:
  namespace: karthik
  name: resource-Pod
  labels:
    name: resource-Pod
    environment: DEV
    createdBy: karthik
spec:
  containers:
    - name: tomcat
      image: tomcat:latest
  resources:
    request:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "100m"
      memory: "100Mi"
      ports:
        - containerPort: 8080
