apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: multi-containers
    environment: Dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: tomcat
      image: tomcat:latest
    - name: almalinux
      image: almalinux:9
      ports:
        - containerPort: 80
        - containerPort: 8080
      command: ["sleep", "2000"]
