kind: Pod
apiVersion: v1
metadata:
  namespace: karthik
  name: nginx-pod
  labels:
    name: nginx
    environment: PROD
    createdBy: karthik
    dispatcher: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
