kind: Pod
apiVersion: v1
metadata:
  name: resource-pod
  labels:
    name: resources
    environment: PROD
    createdBY: karthik
spec:
  containers:
    - name: tomcat
      image: tomcat:latest
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "100m"
          memory: "100Mi"
      ports:
        - containerPort: 8080
