kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  labels:
    name: nginx
    environment: Dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
