kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: karthik
  name: deployment-pods
  labels:
    name: deployment
    environment: PROD
    type: frontend
    face: normal
spec:
  replicas: 5
  selector:
    matchLabels:
      name: deployment
      environment: PROD
      type: frontend
      face: normal
  template:
    metadata:
      name: deployment-pods
      labels:
        name: deployment
        environment: PROD
        type: frontend
        face: normal
    spec:
      containers:
        - name: tomcat
          image: tomcat:latest
