kind: Pod
apiVersion: v1
metadata:
  name: nginx-Pod
  labels:
    name: nginx
    enviornment: Dev
    createdBy: karthik
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: tomcat
      image: tomcat
