kind: Pod
apiVersion: v1
metadata:
  namespace: karthik
  name: nginx-pod
  labels:
    name: frontend
    environment: PROD
    createdBy: karthik
    flag: practice
spec:
  containers:
    - name: nginx-containers
      image: nginx-latest
