kind: Pod
apiVersion: v1
metadata:
  namespace: TCL
  name: nginx-pod
  labels:
    name: nginx-pod-loadbalancer
    face: frontend
    environment: PROD
    createdBy: karthik
spec:
  containers:
    - name: nginx
      image: nginx:latest
