kind: Pod
apiVersion: v1
metadata:
  name: multi-container-pod
  labels:
    name: multi-containers
    environmet: Dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: tomcat
      image: tomcat:latest
    - name: almalinux
      image: amlalinux:9
  ports:
    - containerPort: 80
    - containerPort: 8080
  command: ["sleep", "2000"]
