kind: Pod
apiVersion: v1
meatadata:
  namespace: karthik
  name: nginx-pod
  labels:
    name: frontend
    project: expense
    component: frontend
    environment: Dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
