kind: Service
apiVersion: v1
metadata:
  name:space: tcl
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    name: nginx-pod-loadbalancer
    face: frontend
    environment: PROD
    createdBy: karthik
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 31655
