kind: Service
apiVersion: v1
metadata:
  namespace: karthik
  name: nodeport-service
spec:
  type: NodePort
selector:
  name: frontend
  environment: PROD
  createdBy: karthik
  flag: practice
ports:
  - protocl: TCP
    port: 80
    targetPort: 80
    nodePort: 32751
