kind: Service
apiVersion: v1
metadata:
  namespace: karthik
  name: node-port-service
spec:
  type: NodePort
  selector:
    name: tomcat
    environment: PROD
    createdBy: karthik-kandagaddala
    date: 17-june-2025
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 32765
