kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: Dev
  ports:
    - portocol: TCP
      port: 80
      targetPort: 80
