kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
  labels:
    name: nginx & almalinux
    environment: Dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "2000"]
