kind: Pod
apiVersion: v1
metadata:
  name: multi-containers #pod name
  labels:
    name: nginx-almalinux
    environment: Dev
spec:
  containers:
    - name: nginx #container name-1
      image: nginx:latest
    - name: almalinux #container name-2
      image: almalinux:9
      command: ["sleep", "2000"]
