---
apiVersion: v1
kind: Pod
metadata:
  namespace: karthik
  name: env-test-pod
spec:
  containers:
    - name: env-test
      image: nginx:latest
      env:
        - name: course
          value: "kubernetes"
        - name: duration
          value: "20-Hours"
      ports:
        - containerPort: 80
