kind: Service
apiVersion: v1
metadata:
  namespace: karthik
  name: nginx-service
spec: #we are not giving any type means consider as cluster IP or service IP
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: Dev
  ports:
    - protocol: TCP
      port: 80 #service-port
      targetPort: 80 #target-port
