kind: Service
apiVersion: v1
metadata:
  name: Nginx-Node-port
Spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: Dev
  ports:
    - protocl: TCP
      port: 80 #service-port
      targetPort: 80 #target-pot
      nodePort: 32750 #if you dont mention means randomly it will open one port so fix your own port
