kind: Service
apiVersion: v1
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer #it will works only cloud
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: Dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32755
