kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-pod-replicas
  labels:
    name: nginx-pod
    project: TCL
    environment: Dev
    face: frontend
  spec:
    replicas: 3
    selector:
      matchLabels:
        name: nginx-pod
        project: TCL
        environment: Dev
        face: frontend
  template:
    metadata:
      labels:
        name: nginx-pod
        project: TCL
        environment: Dev
        face: frontend
    spec:
      containers:
        - name: nginx
          imge: nginx:latest
