apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: karthik-proj
  region: us-east-1

managedNodegroups:
  - name: karthik-proj
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
