apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

addons:
  - name: eks-pod-identity-agent
    version: v1.3.0
  - name: vpc-cni
    version: v1.18.2
    useDefaultPodIdentityAssociations: true

iam:
  withOIDC: true

managedNodegroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
