apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-2
  region: us-east-1

iam:
  withOIDC: true

addons:
  - name: eks-pod-identity-agent
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

managedNodegroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
