apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
name: wonderful-lofi-walrus
region: us-east-1

managedNodegroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
